language: python
python:
  - "2.7"

before_install:
  - "npm install -g bower"

# command to install dependencies
install:
  - "pip install Fabric path.py"
  - "fab dependencies"

# command to run tests
script: "fab test"
